laserperception_multisweep_builder:
  ros__parameters:
    raw_points_topic: /laserperception/points_raw
    model_ready_topic: /laserperception/points_model_ready
    fixed_frame: nuscenes_map
    target_frame: ""
    max_historical_sweeps: 10
    transform_timeout_sec: 0.2
    history_reset_gap_sec: 0.0
    tf_cache_time_sec: 10.0
    raw_qos_depth: 5
    model_ready_qos_depth: 1

laserperception_nuscenes_raw_replay:
  ros__parameters:
    raw_points_topic: /laserperception/points_raw
    sample_token: 07fad91090c746ccaa1b2bdb55329e20
    max_historical_sweeps: 10
    publish_period_sec: 0.25
    fixed_frame: nuscenes_map
    ego_frame: nuscenes_ego
    lidar_frame: nuscenes_lidar_top
    raw_qos_depth: 5

laserperception_detector:
  ros__parameters:
    input_topic: /laserperception/points_model_ready
    output_topic: /laserperception/detections
    marker_topic: /laserperception/markers
    publish_markers: true
    input_qos_depth: 1
    input_reliability: best_effort
    output_qos_depth: 5
    output_reliability: reliable
    engine_path: ""
    voxelization_mode: exact_fast
    provenance_mode: live
